### ISSUE TITLE
ModuleNotFoundError: No module named 'defconQt.controls.accordionBox'

### ISSUE THREAD

**Issue by clauseggers** [trufont/trufont#495] opened 2017-09-26 09:10 UTC
Installing from `pip` gives me this when I run `trufont`:
```
Traceback (most recent call last):
  File "/home/claus/.local/bin/trufont", line 7, in <module>
    from trufont.__main__ import main
  File "/home/claus/.local/virtualenv/trufont/venv/lib/python3.6/site-packages/trufont/__main__.py", line 4, in <module>
    from trufont.objects.application import Application
  File "/home/claus/.local/virtualenv/trufont/venv/lib/python3.6/site-packages/trufont/objects/application.py", line 13, in <module>
    from trufont.windows.inspectorWindow import InspectorWindow
  File "/home/claus/.local/virtualenv/trufont/venv/lib/python3.6/site-packages/trufont/windows/inspectorWindow.py", line 1, in <module>
    from defconQt.controls.accordionBox import AccordionBox
ModuleNotFoundError: No module named 'defconQt.controls.accordionBox'
```

**Comment by adrientetar** [comment] 2017-09-26 09:20
Duplicate of #442. Basically I released new versions of defconQt but trufont is an old release.

What you should do is:

git clone https://github.com/trufont/trufont
cd trufont
pip install -r requirements.txt
pip install -e .
trufont

**Closed by adrientetar** 2017-09-26 09:20 UTC

**Comment by clauseggers** [comment] 2017-09-26 09:38
Thanks, but now I get this exception:
```
pip install -r requirements.txt
Collecting pyqt5==5.9 (from -r requirements.txt (line 1))
  Using cached PyQt5-5.9-5.9.1-cp35.cp36.cp37-abi3-manylinux1_x86_64.whl
Collecting fonttools==3.15.1 (from -r requirements.txt (line 2))
  Using cached fonttools-3.15.1-py2.py3-none-any.whl
Collecting ufoLib==2.1.0 (from -r requirements.txt (line 3))
  Using cached ufoLib-2.1.0-py2.py3-none-any.whl
Collecting defcon==0.3.4 (from -r requirements.txt (line 4))
  Using cached defcon-0.3.4-py2.py3-none-any.whl
Collecting defconQt==0.5.4 (from -r requirements.txt (line 5))
  Using cached defconQt-0.5.4-py2.py3-none-any.whl
Collecting ufo-extractor==0.2.0 (from -r requirements.txt (line 6))
  Using cached ufo_extractor-0.2.0-py2.py3-none-any.whl
Collecting ufo2ft==0.6.2 (from -r requirements.txt (line 7))
  Using cached ufo2ft-0.6.2-py2.py3-none-any.whl
Collecting booleanOperations==0.7.1 (from -r requirements.txt (line 8))
  Using cached booleanOperations-0.7.1-py2.py3-none-any.whl
Collecting hsluv==0.0.2 (from -r requirements.txt (line 9))
  Downloading hsluv-0.0.2-py2.py3-none-any.whl
Collecting brotli==0.6.0 (from -r requirements.txt (line 10))
  Downloading Brotli-0.6.0-cp36-cp36m-manylinux1_x86_64.whl (922kB)
    100% |████████████████████████████████| 931kB 924kB/s 
Collecting sip<4.20,>=4.19.3 (from pyqt5==5.9->-r requirements.txt (line 1))
  Using cached sip-4.19.3-cp36-cp36m-manylinux1_x86_64.whl
Collecting compreffor>=0.4.5 (from ufo2ft==0.6.2->-r requirements.txt (line 7))
  Using cached compreffor-0.4.5-cp36-cp36m-manylinux1_x86_64.whl
Collecting cu2qu>=1.2.0 (from ufo2ft==0.6.2->-r requirements.txt (line 7))
  Using cached cu2qu-1.2.0-py2.py3-none-any.whl
Collecting pyclipper>=1.0.5 (from booleanOperations==0.7.1->-r requirements.txt (line 8))
  Using cached pyclipper-1.0.6-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: sip, pyqt5, fonttools, ufoLib, defcon, defconQt, ufo-extractor, compreffor, cu2qu, ufo2ft, pyclipper, booleanOperations, hsluv, brotli
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.6/site-packages/sip.so'
```
Can I install this without root?

**Comment by adrientetar** [comment] 2017-09-26 09:41
iirc you can use pip install --user to install in local dir.

**Comment by clauseggers** [comment] 2017-09-26 09:56
Yes, that did the trick. Merci.
