### ISSUE TITLE
Pen tool: Crash when pressing “delete” while drawing a path

### ISSUE THREAD

**Issue by brawer** [trufont/trufont#239] opened 2016-02-09 20:49 UTC
TruFont 0.20 crashes when pressing “delete” while drawing a path with the Pen tool.

Steps to reproduce:

1. open TrueFont 0.20;
2. double-click on any glyph in “Untitled.ufo”;
3. select the Pen tool;
4. click into the glyph window to start a path;
5. click a second time into the glyph window at a slightly different position;
6. press the “delete” key.

Expected: The last point should get deleted.
Observed: TruFont crashes.
Platform: MacOS 10.11.3, perhaps other too.

**Comment by adrientetar** [comment] 2016-02-09 20:51
@brawer This works for me with the latest version &ndash; again, I'd advise running from source until new release comes in, many bugs have been fixed and the glyphView was completely rewritten! Thanks.

**Comment by adrientetar** [comment] 2016-02-10 19:28
Fixed in master.

**Closed by adrientetar** 2016-02-10 19:28 UTC

**Comment by adrientetar** [comment] 2016-03-13 10:49
@brawer I have new app release [here](https://github.com/trufont/trufont/releases/tag/0.3.0) if you want to give it a try.

**Comment by davelab6** [comment] 2016-03-13 20:07
I can't reproduce this with 0.3.0
