### ISSUE TITLE
Crash while drawing

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#255] opened 2016-03-30 22:38 UTC
on dcc430b 

```
Traceback (most recent call last):
  File "/Users/Pathum/src/github.com/trufont/trufont/Lib/defconQt/glyphView.py", line 1030, in mousePressEvent
    self._redirectEvent(event, self._currentTool.mousePressEvent, True)
  File "/Users/Pathum/src/github.com/trufont/trufont/Lib/defconQt/glyphView.py", line 1002, in _redirectEvent
    callback(event)
  File "/Users/Pathum/src/github.com/trufont/trufont/Lib/defconQt/tools/selectionTool.py", line 261, in mousePressEvent
    self._computeLineClick(event.localPos())
  File "/Users/Pathum/src/github.com/trufont/trufont/Lib/defconQt/tools/selectionTool.py", line 100, in _computeLineClick
    prev.x, prev.y, point.x, point.y, pos.x(), pos.y())
  File "/Users/Pathum/src/github.com/trufont/trufont/Lib/defconQt/util/bezierMath.py", line 45, in lineDistance
    projX, projY = lineProjection(x1, y1, x2, y2, x, y)
TypeError: 'NoneType' object is not iterable
/Users/Pathum/src/github.com/trufont/trufont.command: line 2: 83796 Abort trap: 6
```

**Comment by anthrotype** [comment] 2016-03-31 06:41
Duplicate of #254

**Closed by anthrotype** 2016-03-31 06:41 UTC

**Comment by pathumego** [comment] 2016-04-12 09:33
Probably the same issue, IDK, just posting for record.
```
Traceback (most recent call last):
  File "/Users/Pathum/src/github.com/trufont/trufont/Lib/defconQt/glyphView.py", line 1030, in mousePressEvent
    self._redirectEvent(event, self._currentTool.mousePressEvent, True)
  File "/Users/Pathum/src/github.com/trufont/trufont/Lib/defconQt/glyphView.py", line 1002, in _redirectEvent
    callback(event)
  File "/Users/Pathum/src/github.com/trufont/trufont/Lib/defconQt/tools/selectionTool.py", line 261, in mousePressEvent
    self._computeLineClick(event.localPos())
  File "/Users/Pathum/src/github.com/trufont/trufont/Lib/defconQt/tools/selectionTool.py", line 100, in _computeLineClick
    prev.x, prev.y, point.x, point.y, pos.x(), pos.y())
  File "/Users/Pathum/src/github.com/trufont/trufont/Lib/defconQt/util/bezierMath.py", line 45, in lineDistance
    projX, projY = lineProjection(x1, y1, x2, y2, x, y)
TypeError: 'NoneType' object is not iterable
/Users/Pathum/src/github.com/trufont/trufont.command: line 2: 64951 Abort trap: 6 

```
