### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#186] opened 2016-01-05 10:00 UTC
When I try to open a glyph this happnes.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.3.0-py3.5.egg/defconQt/glyphView.py", line 810, in paintEvent
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.3.0-py3.5.egg/defconQt/glyphView.py", line 707, in drawFillAndStroke
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.3.0-py3.5.egg/defconQt/util/drawing.py", line 297, in drawGlyphFillAndStroke
  File "/Users/Pathum/src/github.com/trufont/trufont/src/defcon/Lib/defcon/objects/base.py", line 337, in getRepresentation
    representation = factory["factory"](self, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.3.0-py3.5.egg/defconQt/representationFactories/glyphViewFactory.py", line 17, in NoComponentsQPainterPathFactory
  File "/Users/Pathum/src/github.com/trufont/trufont/src/defcon/Lib/defcon/objects/glyph.py", line 367, in draw
    from ufoLib.pointPen import PointToSegmentPen
ImportError: cannot import name 'PointToSegmentPen'
Abort trap: 6
```

**Comment by adrientetar** [comment] 2016-01-05 11:24
Duplicate of #185, no need to report the same issue multiple times.

**Closed by adrientetar** 2016-01-05 11:24 UTC

**Comment by adrientetar** [comment] 2016-01-05 11:33
If you have a different traceback of the same issue you can post as a comment on the other one.

**Comment by pathumego** [comment] 2016-01-05 11:48
@adrientetar Cool didnt realise its the same issue :+1:
