### ISSUE TITLE
Crash while using Trackpad on Mac

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#160] opened 2015-12-18 22:20 UTC
I think I was trying to see if pinch to zoom works, but couldnt reproduce.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.2.0-py3.5.egg/defconQt/glyphView.py", line 798, in paintEvent
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.2.0-py3.5.egg/defconQt/glyphView.py", line 697, in drawFillAndStroke
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.2.0-py3.5.egg/defconQt/util/drawing.py", line 296, in drawGlyphFillAndStroke
  File "/Users/Pathum/src/github.com/trufont/trufont/src/defcon/Lib/defcon/objects/base.py", line 337, in getRepresentation
    representation = factory["factory"](self, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.2.0-py3.5.egg/defconQt/representationFactories/glyphViewFactory.py", line 17, in NoComponentsQPainterPathFactory
  File "/Users/Pathum/src/github.com/trufont/trufont/src/defcon/Lib/defcon/objects/glyph.py", line 369, in draw
    self.drawPoints(pointPen)
  File "/Users/Pathum/src/github.com/trufont/trufont/src/defcon/Lib/defcon/objects/glyph.py", line 379, in drawPoints
    contour.drawPoints(pointPen)
  File "/usr/local/lib/python3.5/site-packages/defconQt-0.2.0-py3.5.egg/defconQt/objects/defcon.py", line 237, in drawPoints
  File "/Users/Pathum/src/github.com/trufont/trufont/src/robofab/Lib/robofab/pens/pointPen.py", line 97, in endPath
    self._flushContour(segments)
  File "/Users/Pathum/src/github.com/trufont/trufont/src/robofab/Lib/robofab/pens/adapterPens.py", line 47, in _flushContour
    assert len(points) == 1
AssertionError
Abort trap: 6
```

**Comment by adrientetar** [comment] 2016-01-08 09:45
Duplicate of #169.

**Closed by adrientetar** 2016-01-08 09:45 UTC
Labels: I-crash
