### ISSUE TITLE
Matra reorganisation doesn't work (devanagari issue)

### ISSUE THREAD

**Issue by jbmorizot** [trufont/trufont#491] opened 2017-09-11 08:26 UTC
Self explanatory. The shaping engine have to place the I matra before the letter even if the input comes after (प+  ि becomes रि).

**Comment by khaledhosny** [comment] 2017-09-11 09:04
This is probably the same as #490, failure to set correct script will cause HarfBuzz not to use script-specific logic.

**Comment by adrientetar** [comment] 2017-09-11 10:43
Duplicate of #490.

**Closed by adrientetar** 2017-09-11 10:43 UTC
