### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#298] opened 2016-07-15 16:20 UTC
I was trying out close contour on `Version 0.4.0 88f1b1d`

```
Traceback (most recent call last):
  File "/Users/Pathum/src/github.com/trufont/.venv/src/defconqt/Lib/defconQt/controls/glyphCellView.py", line 278, in paintEvent
    pixmap = self._getCurrentRepresentation(glyph)
  File "/Users/Pathum/src/github.com/trufont/.venv/src/defconqt/Lib/defconQt/controls/glyphCellView.py", line 91, in _getCurrentRepresentation
    return glyph.getRepresentation(name, **args)
  File "/Users/Pathum/src/github.com/trufont/.venv/src/defcon/Lib/defcon/objects/base.py", line 338, in getRepresentation
    representation = factory["factory"](self, **kwargs)
  File "/Users/Pathum/src/github.com/trufont/.venv/lib/python3.5/site-packages/trufont/representationFactories/glyphCellFactory.py", line 18, in TFGlyphCellFactory
    return obj.getPixmap()
  File "/Users/Pathum/src/github.com/trufont/.venv/src/defconqt/Lib/defconQt/representationFactories/glyphCellFactory.py", line 106, in getPixmap
    self.drawCellGlyph(painter)
  File "/Users/Pathum/src/github.com/trufont/.venv/src/defconqt/Lib/defconQt/representationFactories/glyphCellFactory.py", line 179, in drawCellGlyph
    path = self.glyph.getRepresentation("defconQt.QPainterPath")
  File "/Users/Pathum/src/github.com/trufont/.venv/src/defcon/Lib/defcon/objects/base.py", line 338, in getRepresentation
    representation = factory["factory"](self, **kwargs)
  File "/Users/Pathum/src/github.com/trufont/.venv/src/defconqt/Lib/defconQt/representationFactories/qPainterPathFactory.py", line 26, in QPainterPathFactory
    glyph.draw(pen)
  File "/Users/Pathum/src/github.com/trufont/.venv/src/defcon/Lib/defcon/objects/glyph.py", line 414, in draw
    self.drawPoints(pointPen)
  File "/Users/Pathum/src/github.com/trufont/.venv/src/defcon/Lib/defcon/objects/glyph.py", line 424, in drawPoints
    contour.drawPoints(pointPen)
  File "/Users/Pathum/src/github.com/trufont/.venv/lib/python3.5/site-packages/trufont/objects/defcon.py", line 409, in drawPoints
    pointPen.endPath()
  File "/Users/Pathum/src/github.com/trufont/.venv/src/ufolib/Lib/ufoLib/pointPen.py", line 132, in endPath
    self._flushContour(segments)
  File "/Users/Pathum/src/github.com/trufont/.venv/src/ufolib/Lib/ufoLib/pointPen.py", line 178, in _flushContour
    assert len(points) == 1, "illegal line segment point count: %d" % len(points)
AssertionError: illegal line segment point count: 3

```

**Comment by adrientetar** [comment] 2016-07-15 17:20
If you can get a screencast so I can see what leads to the crash, that would be helpful. Thanks.

**Comment by adrientetar** [comment] 2017-03-19 15:16
Closing for the time being as I have no way to reproduce. Hopefully is fixed since then.

**Closed by adrientetar** 2017-03-19 15:16 UTC
Labels: I-crash

**Comment by pathumego** [comment] 2017-03-19 19:11
@adrientetar Thanks! its fixed. New UI is looking real good!
