### ISSUE TITLE
Crash #3

### ISSUE THREAD

**Issue by insanetesterftw** [trufont/trufont#305] opened 2016-07-25 10:58 UTC
Windows 7 64
TruFont 0.4.0

Steps:

1) Import font (pfb)
2) Message is shown:

>TruFont encountered a problem and must shutdown.
Unsupported operand type(s) for *: 'NoneType' and 'float'

>Traceback (most recent call last):
  File "c:\users\admin\downloads\adrientetar-realdefconqt-3f75bb4dd9e7\lib\defconQt\controls\glyphCellView.py", line 274, in paintEvent
  File "c:\users\admin\downloads\adrientetar-realdefconqt-3f75bb4dd9e7\lib\defconQt\controls\glyphCellView.py", line 87, in _getCurrentRepresentation
  File "C:\Python34\lib\site-packages\defcon\objects\base.py", line 337, in getRepresentation
  File "C:\Users\Admin\Downloads\trufont\Lib\trufont\representationFactories\glyphCellFactory.py", line 17, in TFGlyphCellFactory
  File "C:\Users\Admin\Downloads\trufont\Lib\trufont\representationFactories\glyphCellFactory.py", line 28, in __init__
  File "c:\users\admin\downloads\adrientetar-realdefconqt-3f75bb4dd9e7\lib\defconQt\representationFactories\glyphCellFactory.py", line 77, in __init__
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

PS: Each time it crashes TruFont fails to remember its last opened folder from the IMPORT command.

**Comment by adrientetar** [comment] 2016-07-25 16:09
Duplicate of #292 #268, this is already fixed.

**Closed by adrientetar** 2016-07-25 16:09 UTC
