### ISSUE TITLE
Version on PyPI is outdated

### ISSUE THREAD

**Issue by probonopd** [trufont/trufont#622] opened 2019-01-02 11:17 UTC
https://pypi.org/project/trufont/#history has 0.5.1.dev1  as the "latest". It cannot be installed due to the known `ModuleNotFoundError: No module named 'defconQt.controls.accordionBox'`
 issue.

Reference:
https://github.com/linuxdeploy/linuxdeploy-plugin-conda/issues/11#issuecomment-450837246

**Comment by adrientetar** [comment] 2019-01-23 13:35
Duplicate of #442

**Closed by adrientetar** 2019-01-23 13:35 UTC
